---
- hosts: picluster_master_nodes_without_boot_strap
#- hosts: picluster_worker_nodes
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - /root/kubernetes_vanilla_ansible/kubernetes_cluster_create_vars.yaml

  tasks:
    - name: Pulldown latest kubernetes images
      ansible.builtin.shell: kubeadm config images pull
      args:
        executable: /bin/bash
      register: out

    - name: Join kubernetes cluster aditional master node {{ ansible_facts["hostname"] }}
      ansible.builtin.shell: echo "kubeadm join {{ bootstrap_ip }} --token {{ bootstrap_token }} --discovery-token-ca-cert-hash sha256:{{ sha256_hash }} --control-plane --certificate-key {{ certificate_key }}"
      args:
        executable: /bin/bash
      register: out

    - debug: var=out.stderr_lines
