---
- hosts: picluster
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install required packages for containerd and docker-ce
      ansible.builtin.apt:
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
