---
- hosts: picluster
  gather_facts: yes
  become: yes

  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Install required packages for kubernetes
      ansible.builtin.apt:
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - kubelet
        - kubeadm
        - kubectl

    - name: Hold kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Hold kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
