---
- hosts: picluster
  gather_facts: no
  become: yes

  tasks:
    - name: Install required packages for kubernetes
      ansible.builtin.apt:
        name: "{{ packages }}" 
        state: present
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
        - atop
        - sysstat

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
