---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes

  tasks:

    - name: Check whether /boot/firmware/cmdline.txt contains "cgroup_memory"
      command: grep -Fxq "cgroup_memory" /boot/firmware/cmdline.txt
      register: checkmyconf
      check_mode: no
      ignore_errors: yes
      changed_when: no

    - name: greet
      debug: msg="Hello, world!"
      when: checkmyconf.rc == 0

    - name: Configure boot parameters to support memory cgroups (WARNING NOT IDEMPOTENT!!!)
      when: checkmyconf.rc == 0
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: "^(.*serial.*)$"
        line: '\1 cgroup_enable=memory cgroup_memory=1'
        state: present