---
- hosts: picluster
  gather_facts: no
  become: yes
  vars:
    sandbox_image_version: '3.9'

  tasks:
    - name: Set containerd settings to defaults 
      ansible.builtin.shell: /usr/bin/containerd config default > /etc/containerd/config.toml 

    - name: Enable the CRI plugin to support kubernetes
      lineinfile:
        path: /etc/containerd/config.toml
        search_string: SystemdCgroup
        line: '            SystemdCgroup = true'

    - name: Change sandbox image version to recommended version
      lineinfile:
        path: /etc/containerd/config.toml
        search_string: sandbox_image
        line: '    sandbox_image = "registry.k8s.io/pause:{{ sandbox_image_version }}"'

    - name: Reboot the server.
      ansible.builtin.reboot:
