---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes

  tasks:
    - name: Configure boot parameters to support memory cgroups
      lineinfile:
        path: /boot/firmware/cmdline.txt
        search_string: console
        line: '\1,cgroup_enable=memory cgroup_memory=1'

#    - name: Reboot the server.
#      ansible.builtin.reboot:
