---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes

  tasks:
    - name: Configure boot parameters to support memory cgroups
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: "^(.*cgroup_memory.*)$"
        line: '\1 cgroup_enable=memory cgroup_memory=1'
        state: present