---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes
  serial: 2

  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Reboot the server.
      ansible.builtin.reboot:
        reboot_command: systemctl reboot
        boot_time_command: uptime | cut -d ' ' -f 5

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes