---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes

  tasks:

    - name: Check whether /boot/firmware/cmdline.txt contains "cgroup_memory"
      command: grep "cgroup_memory" /boot/firmware/cmdline.txt
      register: checkmyconf
      check_mode: no
      ignore_errors: yes
      changed_when: no

    - name: Configure boot parameters to support memory cgroups if returncode is 1 or failed from task above
      when: checkmyconf.rc == 1
      lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: yes
        regexp: "^(.*serial.*)$"
        line: '\1 cgroup_enable=memory cgroup_memory=1'
        state: present