---
- hosts: "{{ variable_host | default('picluster') }}"
  gather_facts: no
  become: yes

  tasks:
    - name: Release kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: install

    - name: Release kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: install

    - name: Release kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: install

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Hold kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Hold kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
